Growth - Auras, Effects, and Behaviors
parkerhams/SystemsStudyGame pull request #17
Opened 2019-04-08 12:13 UTC by parkerhams

Overall, it is not behaving how intended. The Tree model - the RedFirTree prefab - is not scaling the model, but it *is* scaling the trigger area around the tree. As such, I made a debug version of the prefab with a simple sphere - and the sphere does scale. 

I think it might have something to do with the ways the meshes are working in the tree model itself? Since the sphere object has a mesh renderer and collider by default, and the tree model does on the children objects, it makes me think it has something to do with that. 

But please let me know ways you think I could make it better!!!

2019-04-08 16:22 UTC, dantogno requested changes
@parkerhams Nice progress. Work on replying or committing changes to answer all of my questions. My goal is to understand your intent clearly, then we can start focusing on functionality. Keep up the good work!

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +public class FoliageGrowth : MonoBehaviour
Add a summary for the whole class with the <summary> tag  (hotkey: three forward slashes in visual studio)  https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/summary

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("max scale meant to be controlled in editor - biggest size it can get")]
"The biggest size it can get" is sufficient, I'd delete the other words in the tip text.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("checking scales later to then spawn more foliage around tree")]
I don't know what this means. Clarify.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("how quickly it grows")]
How about "growthRate?" Speed implies traveling.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("can it also shrink down - Meant for if player has not completely grown the area")]
I understand the concept from the tip, but I think the name "repeatable" could be clarified. how about `canShrink`?

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    bool isGrowingFoliage;
Clarify

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    static float foliageGrowth = 0.0f;
clarify

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    List<GameObject> spawnedFoliage = new List<GameObject>();
clarify

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +        foliageGrowth += 0.5f * Time.deltaTime;
`.5f` is a magic number here. Make it a variable with a name so I understand what it is.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +                Vector3 temp9 = new Vector3(Mathf.Lerp(minScale.y, maxScale.y, foliageGrowth), 0);
what the heck is `temp9`? come up with a more descriptive name.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +                //FoliageSpawnLerp(foliageSpawn, maxScale, duration);
remove commented out code

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +    public IEnumerator FoliageSpawnLerp(Transform location, Vector3 size, float period)
I'm not sure you are using this currently, but before we delete it, I want to understand more about the intent of the class itself.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/PlayerAuraEmit.cs
> +//The aura trigger surrounding the player that calls for plants to grow.
convert this comment into a summary tag

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/PlayerAuraEmit.cs
> +    Color activatedAuraColor;
These are great names btw 👏

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/PlayerAuraEmit.cs
> +        startLerpTime = Time.time;
what is the intent of `startLerpTime`?

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/PlayerAuraEmit.cs
> +        float t = (Time.time - startLerpTime) * lerpSpeed;
Once I know what `startLerpTime` is meant to be I may have more comments for this.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    [Tooltip("scalableObject is a reference to the location where the foliage should spawn")]
I don't understand the connection between the tip and the name. Clarify.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    private float speed = 2f;
`growthRate` is a better name.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    private float duration = 5f;
wouldn't changing the `growthRate` also change the `duration`? How can the user set them both independently?

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    AudioSource auraAudio;
Use a single audio source with multiple clips (modify the `AudioSource.clip` property). In other words, change the type of this to `AudioClip.` Depending on what game object the `AudioSource` component is on, you can initialize it with `GetComponent` (since there will only be one).

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    AudioSource completedGrowingAudio;
make this an `AudioClip`

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    [SerializeField]
add a quick tooltip

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +            StartCoroutine("Detect");
I prefer passing in the actual method as a parameter as opposed to a string. It enforces typo-free code at compile time

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    public IEnumerator Detect()
definitely add a summary to this. Also, does it need to be public?

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    public IEnumerator Detect()
Once I understand the intent more clearly, you probably want to rename this method as well.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    [Tooltip("base size for any trees or foliage that will scale")]
if this is not a serialized field, don't have a tooltip.

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        minScale = transform.localScale;
maybe you should initialize this in Start

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
>      //takes in two vector 3s - start scale and max scale - and how quickly they lerp as time
make this a proper summary

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
>          float rate = (1.0f / time) * speed;
what is i? what is this rate formula meant to do?

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
>          //this while loop was made while following along with Resistance Code! Not my while loop
what the heck is Resistance Code? 😄

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +            //transform.localScale = Vector3.Lerp(a, b, i);
remove commented out code

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
>              i += Time.deltaTime * rate;
what's this meant to do

2019-04-08 16:22 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        yield return new WaitForSeconds(2f);
magic number `2`. Make it a variable with a name so I know what it is for.

2019-04-08 19:33 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
>          //this while loop was made while following along with Resistance Code! Not my while loop
Just credited the tutorial source 💃

2019-04-08 19:38 UTC, parkerhams commented on Assets/Scripts/FoliageGrowth.cs
> +public class FoliageGrowth : MonoBehaviour
Added! Let me know if it makes sense - I can always make it more detailed or condense it to be readable.

2019-04-08 19:38 UTC, parkerhams commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("max scale meant to be controlled in editor - biggest size it can get")]
Changed it to that!

2019-04-08 19:39 UTC, parkerhams commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("checking scales later to then spawn more foliage around tree")]
"location of spawn areas for more thickness and brush"

2019-04-08 19:39 UTC, parkerhams commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("how quickly it grows")]
renamed to growthRate!

2019-04-08 19:39 UTC, parkerhams commented on Assets/Scripts/FoliageGrowth.cs
> +    [Tooltip("can it also shrink down - Meant for if player has not completely grown the area")]
canShrink makes a lot more sense

2019-04-08 19:39 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +            //transform.localScale = Vector3.Lerp(a, b, i);
removed 👍

2019-04-08 19:40 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +        yield return new WaitForSeconds(2f);
added the particleDuration float variable

2019-04-08 19:42 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
>          float rate = (1.0f / time) * speed;
renamed rate to be scaleRate, renamed i to be iterateLerpRate. 

 float scaleRate = 0.0f;
float iterateLerpRate = (1.0f / time) * speed;

This is meant to take the speed set in the editor and actually scale it upwards by the iterateLerpRate and a factor of Time.deltaTime -- scaleRate += Time.deltaTime * iterateLerpRate;

2019-04-08 19:42 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
>              i += Time.deltaTime * rate;
This is meant to take the speed set in the editor and actually scale it upwards by the iterateLerpRate and a factor of Time.deltaTime -- scaleRate += Time.deltaTime * iterateLerpRate;

2019-04-08 19:54 UTC, dantogno requested changes
@parkerhams A few more things to clarify please!

2019-04-08 19:54 UTC, dantogno commented on Assets/Scripts/FoliageGrowth.cs
> +public class FoliageGrowth : MonoBehaviour
Ok. I get it and I like the idea, but I think we should focus first on the core feature. Don't delete this or anything, I just want to put it on pause.

2019-04-08 19:54 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        float iterateLerpRate = (1.0f / time) * speed;
Better add a summary to iterateLerpRate becaues I'm not totally clear on it  😉

2019-04-08 19:54 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
>      [SerializeField]
Add a summary tag for this class (I guess I can't comment at the top of the class because there are no changes there in this PR)

2019-04-08 19:54 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +    [SerializeField]
I think you could rename `doneGrowingParticles` to something like `growthCompletedParticles`, because it almost sounds like "I'm done growing particles" which is not the intent:
```
if (doneGrowingParticles)
  // Do the next thing now that the particles are done growing.
```

I assume the intent is that these are particles meant to play with the growth process is done.

2019-04-09 02:04 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
>      [SerializeField]
Done!

2019-04-09 02:12 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +        float iterateLerpRate = (1.0f / time) * speed;
I hope this might make some more sense of what it's doing - please let me know if there's another way we could do this that might be more clear of efficient!

"This Enumerator is using scaleLerp to tell the gameObject where to start - and when we reach
  the iterateLerp variable, in this case 1 divided by the passed in time variable multipled by speed,
  we are telling the game objects to stop scaling. While we scale upwards, we scale while we are 
  between the values of scaleRate and iterateLerpRate. We start at a value of 0 here, and once the 
 value reaches the iterateLerpRate value, we stop scaling upwards."

2019-04-09 15:39 UTC, dantogno requested changes
The main issue remaining is that I really don't know what a RepeatLerp or an IterateLerpRate is, and the summaries are not helping me see the light just yet. It's very important to be able to express the intent of this clearly. 

If we can't express the meaning and intent of these clearly, it is a good indication that we need to rethink the approach to how we're implementing the feature.

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        /// <summary>
summary tags have to go on the line just before the thing they are summarizing. So not inside of the method, but just before it.

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        /// <summary>
I think there may be some confusion by the fact that I asked for two summaries here, one for the whole `RepeatLerp` method, and one for the field `iterateLerpRate`.

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +        float iterateLerpRate = (1.0f / time) * speed;
Yeah this is still not clear enough for me to follow and understand easily. Take another pass at naming these things and writing clear summaries for anything where the name is not crystal clear. 

- For example, a normal person is not going to really know what an `iterateLerpRate` is. So it needs a better name and / or a summary. 
- Why would you scale between the values of scaleRate and iterateLerpRate? Wouldn't I scale between the values of the min or starting scale  and the maximum or ending scale?

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +/// The scale leraper class is meant to scale a game object, in this case trees, upwards to a maxScale
Typo "leaper"

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +/// The trees will grow ar a rate of the speed variable over a duration of the duration variable.
typo "ar"

2019-04-09 15:39 UTC, dantogno commented on Assets/Scripts/ScaleLerper.cs
> +/// The trees will grow ar a rate of the speed variable over a duration of the duration variable.
Mathematically, I don't think we can have independent duration, max, and rate variables. If we adjust one, the others are linked and will be adjusted as well. For example, if I am going from 0 to 10 at 1 per second, it's going to take me 10 seconds. I can't have the user change that 10 second duration without changing either the min, max, or rate as well. Does that make sense?

2019-04-09 20:01 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +/// The scale leraper class is meant to scale a game object, in this case trees, upwards to a maxScale
Fixed - thanks for catching that, my bad

2019-04-09 20:02 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +/// The trees will grow ar a rate of the speed variable over a duration of the duration variable.
fixed typo

That makes sense; the player themselves doesn't have the ability to manipulate these values but mathematically if we're using these I definitely want it to be the clearest it can be. If it's better to use one value or change what's here, let me know!

2019-04-09 20:04 UTC, parkerhams commented on Assets/Scripts/ScaleLerper.cs
> +        /// <summary>
Renamed stuff to be more honest about what it does - so RepeatLerp is now **ScaleLerp** because that's what it's doing, scaleRate is now **scaleValue** and iterateLerpRate was not a good name so now it is **increaseRate**. 

Here is the summary for ScaleLerp() coroutine:
 ---SCALELERP SUMMARY---
    /// In the Detect coroutine, we return RepeatLerp once the player enters the trigger area.
    /// When Detect is called, we set the minScale to whatever the growable GameObject's local scale is
    /// in the world space. We then call the couroutine RepeatLerp, which takes in two vector 3's and a float variable.
    /// We pass in minScale and maxScale and the duration, all serialized variables at the top, into our ScaleLerp coroutine.
    /// The ScaleLerp uses two temporary variables - scaleValue, which is 0 and is assigned as our starting point, and 
    /// increaseRate, which is used to see when we tell the GameObject to stop scaling. Our increaseRate value tells
    /// the scaleValue value how much to increase by until it gets to 1 over same length of time that it takes our scaleableObject to 
    /// reach maxScale. In short, while our scaleValue is greater than 0 but less than 1, 
    /// then we tell the object to scale to our a, b, and time values - 
    /// which are actually our minScale, maxScale, and durtion values. The increaseRate value is how we increment
    /// scaleValue to 1 - and when it reaches 1, then we stop scaling. We scale the GameObject in the while loop to by setting the
    /// scaleableObject's localScale to a Vector 3 lerp and passing in the a(minScale), b(maxScale), and time (duration) values.

Here is the summary for the scaleValue and increaseRate temporary variables:
 ----scaleValue and increaseRate summary----
        /// scaleValue is a temporary value used to say that when the scaleableObject is at its minScale, it is at 0, 
        /// and while the scaleableObject grows to its maxScale over the duration variable value, then we scale upwards 
        /// as long as scaleValue is less then 1 in a while loop. We increase scaleValue to 1 by adding Time.deltaTime multipled by
        /// the increaseRate value. increaseRate tells scaleValue to increase to 1 at the same rate that our scaleableObject 
        /// increases from minScale to maxScale - it accounts for the speed at which we've told the scaleable object to grow as well
        /// as the duration of growth through our temporary time variable, which takes in our serialized duration variable 
        /// when we call RepeatLerp() in our Detect() coroutine. While scaleRate is less than 1, scale the gameobject. 
        /// When scaleValue reaches 1 by taking into account the speed and time values, 
        /// then stop growing because that means we've reached our maxScale.

2019-04-30 23:40 UTC, merged